server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD:-changeme}
    sources:
      youtube: false        # desactiva fuente vieja
      bandcamp: true
      soundcloud: true
      http: true
      local: false

plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.15.0"
    repository: "https://maven.lavalink.dev/releases"
